# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{
  AmITyping = "typingTweaks";
  allCallTimers = "callTimer";
  VCSupport = "equicordHelper";
  cleanUserArea = "cleanerChannelGroups";
  dontFilterMe = "anammox";
  questCompleter = "questify";
  questFocused = "questify";
  timelessClips = "clipsEnhancements";
  videoSpeed = "mediaPlaybackSpeed";
}
